# Generated by Django 4.2.4 on 2023-08-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wall', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
